version: '3.8'

networks:
  estufa-network:
    driver: bridge

services:
  mosquitto:
    build:
      context: ./mqtt-broker
      dockerfile: Dockerfile
    container_name: mosquitto-broker
    restart: unless-stopped
    ports:
      - "1883:1883"    # MQTT
      - "9001:9001"    # WebSocket
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    networks:
      - estufa-network
    environment:
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD-SHELL", "timeout 5s mosquitto_pub -h localhost -p 1883 -t 'health/check' -m 'ping' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./src/client_service/frontend
      dockerfile: Dockerfile
    container_name: estufa-frontend
    restart: unless-stopped
    ports:
      - "5173:80"   # host:container (dev preview on 5173 -> nginx 80)
    networks:
      - estufa-network
    depends_on:
      - mosquitto
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  mosquitto_data:
    driver: local
  mosquitto_logs:
    driver: local
